FROM node:20.12.0-alpine3.19

ARG BACKEND_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG JWT_SECRET
ARG CALLBACK_URL
ARG ID_GITHUB
ARG SECRET_GITHUB
ARG DATABASE_URL
ARG ADMIN_USERNAME

ENV BACKEND_URL=${BACKEND_URL}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV JWT_SECRET=${JWT_SECRET}
ENV CALLBACK_URL=${CALLBACK_URL}
ENV ID_GITHUB=${ID_GITHUB}
ENV SECRET_GITHUB=${SECRET_GITHUB}
ENV DATABASE_URL=${DATABASE_URL}
ENV ADMIN_USERNAME=${ADMIN_USERNAME}

WORKDIR /src

COPY package* . 
COPY tsconfig.json .
COPY ./prisma .

RUN npm install --legacy-peer-deps
RUN DATABASE_URL=${DATABASE_URL} npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]